facebook:
  access-token:
  api-version: https://graph.facebook.com/v17.0
  my-number-id: 12
  recipient-number: 1234
  app-id: 22
  version: v17.0
  verify-token: praneeth
  wabaId: 1234567890
spring:
  data:
    mongodb:
      database: whats-app-api
      port: 27017
      username: admin
      password: admin
      authentication-database: admin
      host: localhost

customer-service: http://localhost:8080/customer-registration-service
feign:
  client:
    config:
      customer-service:
        loggerLevel: full
      default:
        loggerLevel: full